spring:
  application:
    name: email-service
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/m_s_email_db?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: madmax.ever@gmail.com
    password: as12as12
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
server:
  port: 7400
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka/
